### ISSUE TITLE
Exception: Unexpected redefinition of symbol: __WINDOWS__, of kind: CursorKind.MACRO_DEFINITION at <SourceLocation file 'C:\\rizin\\include\\librz\\rz_types.h', line 154, column 9>

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-bindgen#3]
```
   [1/4] Generating swig_sources with a custom command
    FAILED: rizin.i
    "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\Scripts\python.EXE" "../../src/main.py" "-o" "rizin.i" "--clang-path" "C:/Program Files/LLVM/bin" "--clang-args" " -resource-dir=C:/Program Files/LLVM/lib/clang/14.0.6" "--rizin-inc-path" "C:rizin/include/librz"
    warning: Files/LLVM/lib/clang/14.0.6: 'linker' input unused [-Wunused-command-line-argument]
    warning: Files/LLVM/lib/clang/14.0.6: 'linker' input unused [-Wunused-command-line-argument]
    warning: Files/LLVM/lib/clang/14.0.6: 'linker' input unused [-Wunused-command-line-argument]
    Traceback (most recent call last):
      File "../../src/main.py", line 96, in <module>
        types_h = Header("rz_types.h")
      File "D:\a\rz-bindgen\rz-bindgen\src\header.py", line 96, in __init__
        f"Unexpected redefinition of symbol: {cursor.spelling}, "
    Exception: Unexpected redefinition of symbol: __WINDOWS__, of kind: CursorKind.MACRO_DEFINITION at <SourceLocation file 'C:\\rizin\\include\\librz\\rz_types.h', line 154, column 9>
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
        main()
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 927, in build_wheel
        return project.wheel(out).name
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 875, in wheel
        wheel = _WheelBuilder(self).build(self._install_plan, self._copy_files, self._build_dir)
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 354, in build
        self._project.build()  # ensure project is built
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 535, in build
        self._meson('compile')
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 477, in _meson
        return self._proc('meson', *args)
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-8vgyyg57\overlay\Lib\site-packages\mesonpy\__init__.py", line 472, in _proc
        subprocess.check_call(list(args))
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.7.9\tools\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: 'C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\Scripts\python.exe' 'C:\Users\runneradmin\AppData\Local\Temp\cibw-run-9lx7lin5\cp37-win_amd64\build\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpx6rpm97_'
    cwd: D:\a\rz-bindgen\rz-bindgen
    Preparing metadata (pyproject.toml): finished with status 'error'
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
```

**Comment by wingdeans** [comment]
Fixed in 97511c0618abaa7644e1faf609ccebbd55db37fe (and 5b985a8f5439cbb66fa7d30bcb7bb3d3901406f0)
