### ISSUE TITLE
 rizin_wrap.cxx:82513:28: error: incompatible pointer types assigning to 'FILE *' (aka '__sFILE *') from 'int *'

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-bindgen#6]
On MacOS: https://github.com/rizinorg/rz-bindgen/runs/7550073649?check_suite_focus=true#step:3:3587
```
 [3/4] Compiling C++ object _rizin.cpython-37m-darwin.so.p/meson-generated_.._rizin_wrap.cxx.o
    FAILED: _rizin.cpython-37m-darwin.so.p/meson-generated_.._rizin_wrap.cxx.o
    c++ -I_rizin.cpython-37m-darwin.so.p -I. -I../.. -I/usr/local/include/librz -I/usr/local/include/librz/sdb -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/Cellar/libuv/1.44.2/include -fcolor-diagnostics -Wall -Winvalid-pch -Wnon-virtual-dtor -O2 -MD -MQ _rizin.cpython-37m-darwin.so.p/meson-generated_.._rizin_wrap.cxx.o -MF _rizin.cpython-37m-darwin.so.p/meson-generated_.._rizin_wrap.cxx.o.d -o _rizin.cpython-37m-darwin.so.p/meson-generated_.._rizin_wrap.cxx.o -c rizin_wrap.cxx
    rizin_wrap.cxx:3808:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    static auto SWIGCmds = std::unordered_map<std::string, std::pair<RzCmdDesc*, CmdDirector*> >();
           ^
    rizin_wrap.cxx:3829:9: warning: variable 'arg' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]
            arg ++;
            ^
    rizin_wrap.cxx:3826:68: note: incremented here
        for (const RzCmdDescArg *arg = help->args; arg && arg->name; ++arg) {
                                                                       ^
    rizin_wrap.cxx:9697:13: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                auto it = SWIGCmds.find(cmd);
                ^
    rizin_wrap.cxx:82513:28: error: incompatible pointer types assigning to 'FILE *' (aka '__sFILE *') from 'int *'
      if (arg1) (arg1)->fdin = arg2;
                               ^~~~
    3 warnings and 1 error generated.
    ninja: build stopped: subcommand failed.
    + meson setup --native-file=/Users/runner/work/rz-bindgen/rz-bindgen/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Library/Frameworks/Python.framework/Versions/3.7 /Users/runner/work/rz-bindgen/rz-bindgen /Users/runner/work/rz-bindgen/rz-bindgen/.mesonpy-ro6em_0b/build
    + meson compile
    Traceback (most recent call last):
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
        main()
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 927, in build_wheel
        return project.wheel(out).name
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 875, in wheel
        wheel = _WheelBuilder(self).build(self._install_plan, self._copy_files, self._build_dir)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 354, in build
        self._project.build()  # ensure project is built
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 535, in build
        self._meson('compile')
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 477, in _meson
        return self._proc('meson', *args)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-gjlzx2g5/overlay/lib/python3.7/site-packages/mesonpy/__init__.py", line 472, in _proc
        subprocess.check_call(list(args))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/bin/python /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-8kqycpvo/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpfeaioqem
    cwd: /Users/runner/work/rz-bindgen/rz-bindgen
    Preparing metadata (pyproject.toml): finished with status 'error'
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  ```

**Comment by wingdeans** [comment]
Fixed in 032461b0a0212953badef5e993df3c9fe325d18e
